###
GET http://localhost:3000/routes


###
GET http://localhost:3000/routes/1



###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "Route 2",
    "source_id": "ElVBdi4gSHVtYmVydG8gZGUgQWxlbmNhciBDYXN0ZWxvIEJyYW5jbyAtIFJvY2hhLCBTw6NvIEdvbsOnYWxvIC0gUkosIDI0NDIwLTA3NSwgQnJhc2lsIi4qLAoUChIJNWEFkN2amQARUuJhzdliffsSFAoSCfPo70DsmpkAEQPp0fRTnQgM",
    "destination_id": "ChIJe1j--oGQmQAR-a_izKn9oms"
}