###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/64e905130c9b067fbe936428

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "Route 7",
    "source_id": "2123",
    "destination_id": "11231"
}